#!/bin/bash

# Check if the first argument (day) is provided
if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <day> [input_file]"
  exit 1
fi

# Check if the first argument is a number between 1 and 25
if ! [[ "$1" =~ ^[1-9]$|^1[0-9]$|^2[0-5]$ ]]; then
  echo "Error: Invalid argument. Please provide a number between 1 and 25 for the day."
  exit 1
fi

# Set the day variable
num=$(printf "%02d" "$1")

# Check if the second argument (input_file) is provided
if [ "$#" -eq 2 ]; then
  input_file="$2"
else
  # Default input path
  input_file="../input/in_2023_${num}"
fi

# Construct the command using the provided or default input file
command="jq -nR -f q${num}.jq $input_file"
echo "Executing command: $command"
eval "$command"
